package br.com.digitaxi.empresa.convenio;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.empresa.empresaconveniada.EmpresaConveniada;
import br.com.digitaxi.empresa.empresataxi.EmpresaTaxi;

/**
 * Convenio generated by hbm2java
 */
public class Convenio implements java.io.Serializable {

	// Fields    

	private int idConvenio;

	private EmpresaConveniada empresaConveniada;

	private EmpresaTaxi empresaTaxi;

	private Set clienteConvenios = new HashSet(0);

	private Set clienteConvenios_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Convenio() {
	}

	/** minimal constructor */
	public Convenio(int idConvenio, EmpresaConveniada empresaConveniada,
			EmpresaTaxi empresaTaxi) {
		this.idConvenio = idConvenio;
		this.empresaConveniada = empresaConveniada;
		this.empresaTaxi = empresaTaxi;
	}

	/** full constructor */
	public Convenio(int idConvenio, EmpresaConveniada empresaConveniada,
			EmpresaTaxi empresaTaxi, Set clienteConvenios,
			Set clienteConvenios_1) {
		this.idConvenio = idConvenio;
		this.empresaConveniada = empresaConveniada;
		this.empresaTaxi = empresaTaxi;
		this.clienteConvenios = clienteConvenios;
		this.clienteConvenios_1 = clienteConvenios_1;
	}

	// Property accessors
	public int getIdConvenio() {
		return this.idConvenio;
	}

	public void setIdConvenio(int idConvenio) {
		this.idConvenio = idConvenio;
	}

	public EmpresaConveniada getEmpresaConveniada() {
		return this.empresaConveniada;
	}

	public void setEmpresaConveniada(EmpresaConveniada empresaConveniada) {
		this.empresaConveniada = empresaConveniada;
	}

	public EmpresaTaxi getEmpresaTaxi() {
		return this.empresaTaxi;
	}

	public void setEmpresaTaxi(EmpresaTaxi empresaTaxi) {
		this.empresaTaxi = empresaTaxi;
	}

	public Set getClienteConvenios() {
		return this.clienteConvenios;
	}

	public void setClienteConvenios(Set clienteConvenios) {
		this.clienteConvenios = clienteConvenios;
	}

	public Set getClienteConvenios_1() {
		return this.clienteConvenios_1;
	}

	public void setClienteConvenios_1(Set clienteConvenios_1) {
		this.clienteConvenios_1 = clienteConvenios_1;
	}

}
