package br.com.digitaxi.ativo.taxi;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.ativo.modelo.Modelo;
import br.com.digitaxi.empresa.empresataxi.EmpresaTaxi;
import br.com.digitaxi.pessoa.proprietario.Proprietario;

/**
 * Taxi generated by hbm2java
 */
public class Taxi implements java.io.Serializable {

	// Fields    

	private int idTaxi;

	private Modelo modelo;

	private EmpresaTaxi empresaTaxi;

	private Proprietario proprietario;

	private Integer ano;

	private String cor;

	private String placa;

	private Set interfaceAvls = new HashSet(0);

	private Set motoristas = new HashSet(0);

	private Set interfaceAvls_1 = new HashSet(0);

	private Set motoristas_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Taxi() {
	}

	/** minimal constructor */
	public Taxi(int idTaxi, Modelo modelo, EmpresaTaxi empresaTaxi,
			Proprietario proprietario) {
		this.idTaxi = idTaxi;
		this.modelo = modelo;
		this.empresaTaxi = empresaTaxi;
		this.proprietario = proprietario;
	}

	/** full constructor */
	public Taxi(int idTaxi, Modelo modelo, EmpresaTaxi empresaTaxi,
			Proprietario proprietario, Integer ano, String cor, String placa,
			Set interfaceAvls, Set motoristas, Set interfaceAvls_1,
			Set motoristas_1) {
		this.idTaxi = idTaxi;
		this.modelo = modelo;
		this.empresaTaxi = empresaTaxi;
		this.proprietario = proprietario;
		this.ano = ano;
		this.cor = cor;
		this.placa = placa;
		this.interfaceAvls = interfaceAvls;
		this.motoristas = motoristas;
		this.interfaceAvls_1 = interfaceAvls_1;
		this.motoristas_1 = motoristas_1;
	}

	// Property accessors
	public int getIdTaxi() {
		return this.idTaxi;
	}

	public void setIdTaxi(int idTaxi) {
		this.idTaxi = idTaxi;
	}

	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	public EmpresaTaxi getEmpresaTaxi() {
		return this.empresaTaxi;
	}

	public void setEmpresaTaxi(EmpresaTaxi empresaTaxi) {
		this.empresaTaxi = empresaTaxi;
	}

	public Proprietario getProprietario() {
		return this.proprietario;
	}

	public void setProprietario(Proprietario proprietario) {
		this.proprietario = proprietario;
	}

	public Integer getAno() {
		return this.ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	public String getCor() {
		return this.cor;
	}

	public void setCor(String cor) {
		this.cor = cor;
	}

	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	public Set getInterfaceAvls() {
		return this.interfaceAvls;
	}

	public void setInterfaceAvls(Set interfaceAvls) {
		this.interfaceAvls = interfaceAvls;
	}

	public Set getMotoristas() {
		return this.motoristas;
	}

	public void setMotoristas(Set motoristas) {
		this.motoristas = motoristas;
	}

	public Set getInterfaceAvls_1() {
		return this.interfaceAvls_1;
	}

	public void setInterfaceAvls_1(Set interfaceAvls_1) {
		this.interfaceAvls_1 = interfaceAvls_1;
	}

	public Set getMotoristas_1() {
		return this.motoristas_1;
	}

	public void setMotoristas_1(Set motoristas_1) {
		this.motoristas_1 = motoristas_1;
	}

}
