package br.com.digitaxi.empresa.empresa;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.controleacesso.usuario.Usuario;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	// Fields    

	private int idEmpresa;

	private Usuario usuario;

	private String nome;

	private String cnpj;

	private String contato;

	private String telefone;

	private String fax;

	private String EMail;

	private String home;

	private String descricao;

	private Set empresaAdministradoras = new HashSet(0);

	private Set empresaOperadoraCelulars = new HashSet(0);

	private Set empresaTaxis = new HashSet(0);

	private Set empresaOperadoraCelulars_1 = new HashSet(0);

	private Set empresaConveniadas = new HashSet(0);

	private Set empresaAdministradoras_1 = new HashSet(0);

	private Set empresaConveniadas_1 = new HashSet(0);

	private Set empresaTaxis_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Empresa() {
	}

	/** minimal constructor */
	public Empresa(int idEmpresa, Usuario usuario) {
		this.idEmpresa = idEmpresa;
		this.usuario = usuario;
	}

	/** full constructor */
	public Empresa(int idEmpresa, Usuario usuario, String nome, String cnpj,
			String contato, String telefone, String fax, String EMail,
			String home, String descricao, Set empresaAdministradoras,
			Set empresaOperadoraCelulars, Set empresaTaxis,
			Set empresaOperadoraCelulars_1, Set empresaConveniadas,
			Set empresaAdministradoras_1, Set empresaConveniadas_1,
			Set empresaTaxis_1) {
		this.idEmpresa = idEmpresa;
		this.usuario = usuario;
		this.nome = nome;
		this.cnpj = cnpj;
		this.contato = contato;
		this.telefone = telefone;
		this.fax = fax;
		this.EMail = EMail;
		this.home = home;
		this.descricao = descricao;
		this.empresaAdministradoras = empresaAdministradoras;
		this.empresaOperadoraCelulars = empresaOperadoraCelulars;
		this.empresaTaxis = empresaTaxis;
		this.empresaOperadoraCelulars_1 = empresaOperadoraCelulars_1;
		this.empresaConveniadas = empresaConveniadas;
		this.empresaAdministradoras_1 = empresaAdministradoras_1;
		this.empresaConveniadas_1 = empresaConveniadas_1;
		this.empresaTaxis_1 = empresaTaxis_1;
	}

	// Property accessors
	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	public String getContato() {
		return this.contato;
	}

	public void setContato(String contato) {
		this.contato = contato;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public String getHome() {
		return this.home;
	}

	public void setHome(String home) {
		this.home = home;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Set getEmpresaAdministradoras() {
		return this.empresaAdministradoras;
	}

	public void setEmpresaAdministradoras(Set empresaAdministradoras) {
		this.empresaAdministradoras = empresaAdministradoras;
	}

	public Set getEmpresaOperadoraCelulars() {
		return this.empresaOperadoraCelulars;
	}

	public void setEmpresaOperadoraCelulars(Set empresaOperadoraCelulars) {
		this.empresaOperadoraCelulars = empresaOperadoraCelulars;
	}

	public Set getEmpresaTaxis() {
		return this.empresaTaxis;
	}

	public void setEmpresaTaxis(Set empresaTaxis) {
		this.empresaTaxis = empresaTaxis;
	}

	public Set getEmpresaOperadoraCelulars_1() {
		return this.empresaOperadoraCelulars_1;
	}

	public void setEmpresaOperadoraCelulars_1(Set empresaOperadoraCelulars_1) {
		this.empresaOperadoraCelulars_1 = empresaOperadoraCelulars_1;
	}

	public Set getEmpresaConveniadas() {
		return this.empresaConveniadas;
	}

	public void setEmpresaConveniadas(Set empresaConveniadas) {
		this.empresaConveniadas = empresaConveniadas;
	}

	public Set getEmpresaAdministradoras_1() {
		return this.empresaAdministradoras_1;
	}

	public void setEmpresaAdministradoras_1(Set empresaAdministradoras_1) {
		this.empresaAdministradoras_1 = empresaAdministradoras_1;
	}

	public Set getEmpresaConveniadas_1() {
		return this.empresaConveniadas_1;
	}

	public void setEmpresaConveniadas_1(Set empresaConveniadas_1) {
		this.empresaConveniadas_1 = empresaConveniadas_1;
	}

	public Set getEmpresaTaxis_1() {
		return this.empresaTaxis_1;
	}

	public void setEmpresaTaxis_1(Set empresaTaxis_1) {
		this.empresaTaxis_1 = empresaTaxis_1;
	}

}
