package br.com.digitaxi.pessoa.celular;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.pessoa.cliente.Cliente;

/**
 * Celular generated by hbm2java
 */
public class Celular implements java.io.Serializable {

	// Fields    

	private int idCelular;

	private Cliente cliente;

	private Set nomeEnderecos = new HashSet(0);

	private Set nomeEnderecos_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Celular() {
	}

	/** minimal constructor */
	public Celular(int idCelular, Cliente cliente) {
		this.idCelular = idCelular;
		this.cliente = cliente;
	}

	/** full constructor */
	public Celular(int idCelular, Cliente cliente, Set nomeEnderecos,
			Set nomeEnderecos_1) {
		this.idCelular = idCelular;
		this.cliente = cliente;
		this.nomeEnderecos = nomeEnderecos;
		this.nomeEnderecos_1 = nomeEnderecos_1;
	}

	// Property accessors
	public int getIdCelular() {
		return this.idCelular;
	}

	public void setIdCelular(int idCelular) {
		this.idCelular = idCelular;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Set getNomeEnderecos() {
		return this.nomeEnderecos;
	}

	public void setNomeEnderecos(Set nomeEnderecos) {
		this.nomeEnderecos = nomeEnderecos;
	}

	public Set getNomeEnderecos_1() {
		return this.nomeEnderecos_1;
	}

	public void setNomeEnderecos_1(Set nomeEnderecos_1) {
		this.nomeEnderecos_1 = nomeEnderecos_1;
	}

}
