package br.com.digitaxi.pessoa.proprietario;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.pessoa.pessoa.Pessoa;

/**
 * Proprietario generated by hbm2java
 */
public class Proprietario implements java.io.Serializable {

	// Fields    

	private int idProprietario;

	private Pessoa pessoa;

	private Set taxis = new HashSet(0);

	private Set taxis_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Proprietario() {
	}

	/** minimal constructor */
	public Proprietario(int idProprietario) {
		this.idProprietario = idProprietario;
	}

	/** full constructor */
	public Proprietario(int idProprietario, Pessoa pessoa, Set taxis,
			Set taxis_1) {
		this.idProprietario = idProprietario;
		this.pessoa = pessoa;
		this.taxis = taxis;
		this.taxis_1 = taxis_1;
	}

	// Property accessors
	public int getIdProprietario() {
		return this.idProprietario;
	}

	public void setIdProprietario(int idProprietario) {
		this.idProprietario = idProprietario;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Set getTaxis() {
		return this.taxis;
	}

	public void setTaxis(Set taxis) {
		this.taxis = taxis;
	}

	public Set getTaxis_1() {
		return this.taxis_1;
	}

	public void setTaxis_1(Set taxis_1) {
		this.taxis_1 = taxis_1;
	}

}
