/*
 * ExplanationMain.java
 *
 * Created on 12 de Abril de 2002, 05:37
 */

package unbbayes.datamining.gui.explanation;

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.lang.*;
import java.net.URL;
import java.util.*;
import javax.help.*;
import javax.swing.*;
import javax.swing.border.*;
import unbbayes.controlador.*;
import unbbayes.fronteira.*;
import unbbayes.jprs.jbn.*;
import unbbayes.io.*;
import unbbayes.util.*;

/**
 *
 * @author  Paulo F. Duarte
 */
public class ExplanationMain extends javax.swing.JInternalFrame {
    
    private static final String NAIVE_ERR = "This is not a NaiveBayes Network!";
    private ProbabilisticNetwork net = null;
    private JFileChooser fileChooser = new JFileChooser(new File(System.getProperty("user.dir")));
    private IGraph netExplanationGraph = null;
    Node selectedNode = null, nodeClass = null;
    ArrayMap phrasesMap = null;
    
    /** Creates new form ExplanationMain */
    public ExplanationMain() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        explanationMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        topicsMenuItem = new javax.swing.JMenuItem();
        typeButtonGroup = new javax.swing.ButtonGroup();
        explanationToolBar = new javax.swing.JToolBar();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        explanationEditSplitPane = new javax.swing.JSplitPane();
        networkPanel = new javax.swing.JPanel();
        explanationPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        phraseLabel = new javax.swing.JLabel();
        phraseScrollPane = new javax.swing.JScrollPane();
        phraseTextArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        triggerTypeRadioButton = new javax.swing.JRadioButton();
        complementaryTypeRadioButton = new javax.swing.JRadioButton();
        naTypeRadioButton = new javax.swing.JRadioButton();
        necessaryTypeRadioButton = new javax.swing.JRadioButton();
        exclusiveTypeRadioButton = new javax.swing.JRadioButton();
        typeLabel = new javax.swing.JLabel();
        
        fileMenu.setMnemonic('F');
        fileMenu.setText("File");
        openMenuItem.setMnemonic('O');
        openMenuItem.setText("Open...");
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/abrir.gif")));
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        
        fileMenu.add(openMenuItem);
        saveMenuItem.setMnemonic('S');
        saveMenuItem.setText("Save Network...");
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.gif")));
        saveMenuItem.setEnabled(false);
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        
        fileMenu.add(saveMenuItem);
        exitMenuItem.setMnemonic('E');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        
        fileMenu.add(exitMenuItem);
        explanationMenuBar.add(fileMenu);
        helpMenu.setMnemonic('H');
        helpMenu.setText("Help");
        topicsMenuItem.setMnemonic('E');
        topicsMenuItem.setText("Help topics...");
        topicsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/help.gif")));
        topicsMenuItem.setEnabled(false);
        topicsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsMenuItemActionPerformed(evt);
            }
        });
        
        helpMenu.add(topicsMenuItem);
        explanationMenuBar.add(helpMenu);
        
        setMaximizable(true);
        setTitle("Explanation");
        setIconifiable(true);
        setResizable(true);
        setClosable(true);
        setName("Explanation");
        setMinimumSize(new java.awt.Dimension(640, 480));
        explanationToolBar.setFloatable(false);
        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/abrir.gif")));
        openButton.setToolTipText("Open a file");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        
        explanationToolBar.add(openButton);
        
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.gif")));
        saveButton.setToolTipText("Save a file");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        
        explanationToolBar.add(saveButton);
        
        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/help.gif")));
        helpButton.setToolTipText("Call help file");
        helpButton.setEnabled(false);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        
        explanationToolBar.add(helpButton);
        
        getContentPane().add(explanationToolBar, java.awt.BorderLayout.NORTH);
        
        statusPanel.setLayout(new java.awt.BorderLayout());
        
        statusPanel.setBorder(new javax.swing.border.TitledBorder("Status"));
        statusLabel.setText("Welcome");
        statusPanel.add(statusLabel, java.awt.BorderLayout.CENTER);
        
        getContentPane().add(statusPanel, java.awt.BorderLayout.SOUTH);
        
        explanationEditSplitPane.setDividerLocation(123);
        explanationEditSplitPane.setDividerSize(1);
        explanationEditSplitPane.setBorder(null);
        explanationEditSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        networkPanel.setLayout(new java.awt.BorderLayout());
        
        networkPanel.setBackground(java.awt.Color.white);
        explanationEditSplitPane.setRightComponent(networkPanel);
        
        explanationPanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));
        
        explanationPanel.setBorder(new javax.swing.border.EtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout(10, 0));
        
        descriptionLabel.setText("Description");
        descriptionLabel.setEnabled(false);
        jPanel1.add(descriptionLabel, java.awt.BorderLayout.WEST);
        
        descriptionScrollPane.setBorder(new javax.swing.border.EtchedBorder());
        descriptionTextArea.setEnabled(false);
        descriptionTextArea.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent evt) {
                descriptionTextAreaUpdate(evt);
            }
            public void insertUpdate(javax.swing.event.DocumentEvent evt) {
                descriptionTextAreaUpdate(evt);
            }
            public void removeUpdate(javax.swing.event.DocumentEvent evt) {
                descriptionTextAreaUpdate(evt);
            }
        });
        descriptionScrollPane.setViewportView(descriptionTextArea);
        
        jPanel1.add(descriptionScrollPane, java.awt.BorderLayout.CENTER);
        
        explanationPanel.add(jPanel1);
        
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));
        
        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));
        
        phraseLabel.setText("Phrase");
        phraseLabel.setEnabled(false);
        jPanel3.add(phraseLabel, java.awt.BorderLayout.WEST);
        
        phraseScrollPane.setBorder(new javax.swing.border.EtchedBorder());
        phraseTextArea.setEnabled(false);
        phraseTextArea.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent evt) {
                phraseTextAreaUpdate(evt);
            }
            public void insertUpdate(javax.swing.event.DocumentEvent evt) {
                phraseTextAreaUpdate(evt);
            }
            public void removeUpdate(javax.swing.event.DocumentEvent evt) {
                phraseTextAreaUpdate(evt);
            }
        });
        phraseScrollPane.setViewportView(phraseTextArea);
        
        jPanel3.add(phraseScrollPane, java.awt.BorderLayout.CENTER);
        
        jPanel2.add(jPanel3);
        
        jPanel4.setLayout(new java.awt.BorderLayout());
        
        jPanel5.setLayout(new java.awt.GridLayout(2, 3));
        
        triggerTypeRadioButton.setText("Trigger");
        typeButtonGroup.add(triggerTypeRadioButton);
        triggerTypeRadioButton.setActionCommand(Node.ExplanationPhrase.TRIGGER_TYPE);
        triggerTypeRadioButton.setEnabled(false);
        triggerTypeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRadiosActionPerformed(evt);
            }
        });
        
        jPanel5.add(triggerTypeRadioButton);
        
        complementaryTypeRadioButton.setText("Complementary");
        typeButtonGroup.add(complementaryTypeRadioButton);
        complementaryTypeRadioButton.setActionCommand(Node.ExplanationPhrase.COMPLEMENTARY_TYPE);
        complementaryTypeRadioButton.setEnabled(false);
        complementaryTypeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRadiosActionPerformed(evt);
            }
        });
        
        jPanel5.add(complementaryTypeRadioButton);
        
        naTypeRadioButton.setSelected(true);
        naTypeRadioButton.setText("N/A");
        typeButtonGroup.add(naTypeRadioButton);
        naTypeRadioButton.setActionCommand(Node.ExplanationPhrase.NA_TYPE);
        naTypeRadioButton.setEnabled(false);
        naTypeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRadiosActionPerformed(evt);
            }
        });
        
        jPanel5.add(naTypeRadioButton);
        
        necessaryTypeRadioButton.setText("Necessary");
        typeButtonGroup.add(necessaryTypeRadioButton);
        necessaryTypeRadioButton.setActionCommand(Node.ExplanationPhrase.NECESSARY_TYPE);
        necessaryTypeRadioButton.setEnabled(false);
        necessaryTypeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRadiosActionPerformed(evt);
            }
        });
        
        jPanel5.add(necessaryTypeRadioButton);
        
        exclusiveTypeRadioButton.setText("Exclusive");
        typeButtonGroup.add(exclusiveTypeRadioButton);
        exclusiveTypeRadioButton.setActionCommand(Node.ExplanationPhrase.EXCLUSIVE_TYPE);
        exclusiveTypeRadioButton.setEnabled(false);
        exclusiveTypeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRadiosActionPerformed(evt);
            }
        });
        
        jPanel5.add(exclusiveTypeRadioButton);
        
        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);
        
        typeLabel.setText("Type");
        typeLabel.setEnabled(false);
        jPanel4.add(typeLabel, java.awt.BorderLayout.WEST);
        
        jPanel2.add(jPanel4);
        
        explanationPanel.add(jPanel2);
        
        explanationEditSplitPane.setLeftComponent(explanationPanel);
        
        getContentPane().add(explanationEditSplitPane, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void typeRadiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeRadiosActionPerformed
        if (selectedNode != null && !selectedNode.equals(nodeClass))
            ((Node.ExplanationPhrase)phrasesMap.get(selectedNode)).type = evt.getActionCommand();
    }//GEN-LAST:event_typeRadiosActionPerformed

    private void phraseTextAreaUpdate(javax.swing.event.DocumentEvent evt) {
        if (selectedNode != null && !selectedNode.equals(nodeClass))
            ((Node.ExplanationPhrase)phrasesMap.get(selectedNode)).strPhrase = phraseTextArea.getText();
    }
    
    private void descriptionTextAreaUpdate(javax.swing.event.DocumentEvent evt) {
        if (selectedNode != null)
            selectedNode.setExplanationDescription(descriptionTextArea.getText());
    }
    
    private void networkPanelMouseClicked(java.awt.event.MouseEvent evt) {
        selectedNode = (Node)netExplanationGraph.getSelected();
        boolean nodeIsSelected = selectedNode != null;
        boolean nodeIsNotClass = nodeIsSelected ? !selectedNode.equals(nodeClass) : true;
        Node.ExplanationPhrase phrase = ((Node.ExplanationPhrase)phrasesMap.get(selectedNode));

        descriptionTextArea.setText(nodeIsSelected ? selectedNode.getExplanationDescription() : "");
        phraseTextArea.setText((nodeIsSelected && nodeIsNotClass) ? phrase.strPhrase : "");
        triggerTypeRadioButton.setSelected((nodeIsSelected && nodeIsNotClass) ? phrase.type.equals(phrase.TRIGGER_TYPE) : false);
        complementaryTypeRadioButton.setSelected((nodeIsSelected && nodeIsNotClass) ? phrase.type.equals(phrase.COMPLEMENTARY_TYPE) : false);
        naTypeRadioButton.setSelected((nodeIsSelected && nodeIsNotClass) ? phrase.type.equals(phrase.NA_TYPE) : true);
        necessaryTypeRadioButton.setSelected((nodeIsSelected && nodeIsNotClass) ? phrase.type.equals(phrase.NECESSARY_TYPE) : false);
        exclusiveTypeRadioButton.setSelected((nodeIsSelected && nodeIsNotClass) ? phrase.type.equals(phrase.EXCLUSIVE_TYPE) : false);

        descriptionLabel.setEnabled(nodeIsSelected);
        descriptionTextArea.setEnabled(nodeIsSelected);
        phraseLabel.setEnabled(nodeIsSelected && nodeIsNotClass);
        phraseTextArea.setEnabled(nodeIsSelected && nodeIsNotClass);
        typeLabel.setEnabled(nodeIsSelected && nodeIsNotClass);
        triggerTypeRadioButton.setEnabled(nodeIsSelected && nodeIsNotClass);
        complementaryTypeRadioButton.setEnabled(nodeIsSelected && nodeIsNotClass);
        naTypeRadioButton.setEnabled(nodeIsSelected && nodeIsNotClass);
        necessaryTypeRadioButton.setEnabled(nodeIsSelected && nodeIsNotClass);
        exclusiveTypeRadioButton.setEnabled(nodeIsSelected && nodeIsNotClass);
    }
    
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        topicsMenuItemActionPerformed(evt);
    }//GEN-LAST:event_helpButtonActionPerformed
    
    private void topicsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsMenuItemActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_topicsMenuItemActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveMenuItemActionPerformed(evt);
    }//GEN-LAST:event_saveButtonActionPerformed
    
    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        openMenuItemActionPerformed(evt);
    }//GEN-LAST:event_openButtonActionPerformed
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        String[] s1 = {"NET"};
        fileChooser = new JFileChooser(fileChooser.getCurrentDirectory());
        fileChooser.setMultiSelectionEnabled(false);
        //adicionar FileView no FileChooser para desenhar ícones de arquivos
        fileChooser.setFileView(new FileIcon(ExplanationMain.this));
        fileChooser.addChoosableFileFilter(new SimpleFileFilter(s1, "Networks (*.net)"));
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            saveNetFile(selectedFile);
        }
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_saveMenuItemActionPerformed
    
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        String[] s1 = {"NET"};
        fileChooser = new JFileChooser(fileChooser.getCurrentDirectory());
        fileChooser.setMultiSelectionEnabled(false);
        //adicionar FileView no FileChooser para desenhar ícones de arquivos
        fileChooser.setFileView(new FileIcon(ExplanationMain.this));
        fileChooser.addChoosableFileFilter(new SimpleFileFilter(s1, "Networks (*.net)"));
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            openNetFile(selectedFile);
            saveButton.setEnabled(true);
            saveMenuItem.setEnabled(true);
        }
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_openMenuItemActionPerformed
    
    private void openNetFile(File selectedFile) {
        try {
            net = new NetIO().load(selectedFile);
            initializeNaiveNet(net);
            NetWindow netWindow = new NetWindow(net);
            networkPanel.add(netWindow.getJspGraph());
            netExplanationGraph = netWindow.getIGraph();
            netExplanationGraph.removeMouseMotionListener(((MouseMotionListener[])netExplanationGraph.getListeners(MouseMotionListener.class))[0]);
            netExplanationGraph.removeKeyListener(((KeyListener[])netExplanationGraph.getListeners(KeyListener.class))[0]);
            netExplanationGraph.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    networkPanelMouseClicked(evt);
                }
            });
            statusLabel.setText("File opened successfully");
        }
        catch (Exception e) {
            net = null; nodeClass = null; phrasesMap = null;
            System.err.print(e.getMessage());
            e.printStackTrace();
            statusLabel.setText(e.getMessage());
        }
    }
    
    private void saveNetFile(File selectedFile) {
        (new NetIO()).save(selectedFile, net);
        statusLabel.setText("File saved successfully");
    }
    
    private void initializeNaiveNet(ProbabilisticNetwork naiveNet) throws Exception {
        NodeList nos = net.getNos();
        int nNos = nos.size(), count = 0;
        for (int i = 0; i < nNos; i++) {
            Node no = (Node)nos.get(i);
            if (no.getParents().size() == 0) {
                nodeClass = no;
                count++;
            }
        }
        if (count != 1)
            throw new Exception(NAIVE_ERR);
        phrasesMap = nodeClass.getPhrasesMap();
        for (int i = 0; i < nNos; i++) {
            Node no = (Node)nos.get(i);
            if (nodeClass.equals(no) || (no.getParents().size() == 1 && nodeClass.equals(no.getParents().get(0)))) {
                if (phrasesMap.get(no) == null)
                    phrasesMap.put(no, new Node.ExplanationPhrase());
            }
            else
                throw new Exception(NAIVE_ERR);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar explanationMenuBar;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem topicsMenuItem;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JToolBar explanationToolBar;
    private javax.swing.JButton openButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JSplitPane explanationEditSplitPane;
    private javax.swing.JPanel networkPanel;
    private javax.swing.JPanel explanationPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel phraseLabel;
    private javax.swing.JScrollPane phraseScrollPane;
    private javax.swing.JTextArea phraseTextArea;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton triggerTypeRadioButton;
    private javax.swing.JRadioButton complementaryTypeRadioButton;
    private javax.swing.JRadioButton naTypeRadioButton;
    private javax.swing.JRadioButton necessaryTypeRadioButton;
    private javax.swing.JRadioButton exclusiveTypeRadioButton;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
    
}
