package br.com.digitaxi.empresa.empresaconveniada;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.empresa.empresa.Empresa;

/**
 * EmpresaConveniada generated by hbm2java
 */
public class EmpresaConveniada implements java.io.Serializable {

	// Fields    

	private int idEmpresaConveniada;

	private Empresa empresa;

	private Set convenios = new HashSet(0);

	private Set convenios_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public EmpresaConveniada() {
	}

	/** minimal constructor */
	public EmpresaConveniada(int idEmpresaConveniada, Empresa empresa) {
		this.idEmpresaConveniada = idEmpresaConveniada;
		this.empresa = empresa;
	}

	/** full constructor */
	public EmpresaConveniada(int idEmpresaConveniada, Empresa empresa,
			Set convenios, Set convenios_1) {
		this.idEmpresaConveniada = idEmpresaConveniada;
		this.empresa = empresa;
		this.convenios = convenios;
		this.convenios_1 = convenios_1;
	}

	// Property accessors
	public int getIdEmpresaConveniada() {
		return this.idEmpresaConveniada;
	}

	public void setIdEmpresaConveniada(int idEmpresaConveniada) {
		this.idEmpresaConveniada = idEmpresaConveniada;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Set getConvenios() {
		return this.convenios;
	}

	public void setConvenios(Set convenios) {
		this.convenios = convenios;
	}

	public Set getConvenios_1() {
		return this.convenios_1;
	}

	public void setConvenios_1(Set convenios_1) {
		this.convenios_1 = convenios_1;
	}

}
