package br.com.digitaxi.pessoa.endereco;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.pessoa.cidade.Cidade;
import br.com.digitaxi.pessoa.pessoa.Pessoa;

/**
 * Endereco generated by hbm2java
 */
public class Endereco implements java.io.Serializable {

	// Fields    

	private int idEndereco;

	private Cidade cidade;

	private Pessoa pessoa;

	private String logradouro;

	private String barrio;

	private String cep;

	private Set nomeEnderecos = new HashSet(0);

	private Set nomeEnderecos_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Endereco() {
	}

	/** minimal constructor */
	public Endereco(int idEndereco, Cidade cidade, Pessoa pessoa) {
		this.idEndereco = idEndereco;
		this.cidade = cidade;
		this.pessoa = pessoa;
	}

	/** full constructor */
	public Endereco(int idEndereco, Cidade cidade, Pessoa pessoa,
			String logradouro, String barrio, String cep, Set nomeEnderecos,
			Set nomeEnderecos_1) {
		this.idEndereco = idEndereco;
		this.cidade = cidade;
		this.pessoa = pessoa;
		this.logradouro = logradouro;
		this.barrio = barrio;
		this.cep = cep;
		this.nomeEnderecos = nomeEnderecos;
		this.nomeEnderecos_1 = nomeEnderecos_1;
	}

	// Property accessors
	public int getIdEndereco() {
		return this.idEndereco;
	}

	public void setIdEndereco(int idEndereco) {
		this.idEndereco = idEndereco;
	}

	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getBarrio() {
		return this.barrio;
	}

	public void setBarrio(String barrio) {
		this.barrio = barrio;
	}

	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public Set getNomeEnderecos() {
		return this.nomeEnderecos;
	}

	public void setNomeEnderecos(Set nomeEnderecos) {
		this.nomeEnderecos = nomeEnderecos;
	}

	public Set getNomeEnderecos_1() {
		return this.nomeEnderecos_1;
	}

	public void setNomeEnderecos_1(Set nomeEnderecos_1) {
		this.nomeEnderecos_1 = nomeEnderecos_1;
	}

}
