package br.com.digitaxi.empresa.empresataxi;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.empresa.empresa.Empresa;

/**
 * EmpresaTaxi generated by hbm2java
 */
public class EmpresaTaxi implements java.io.Serializable {

	// Fields    

	private int idEmpresaTaxi;

	private Empresa empresa;

	private Set interfaceSmses = new HashSet(0);

	private Set convenios = new HashSet(0);

	private Set operadors = new HashSet(0);

	private Set operadors_1 = new HashSet(0);

	private Set interfaceSmses_1 = new HashSet(0);

	private Set convenios_1 = new HashSet(0);

	private Set taxis = new HashSet(0);

	private Set taxis_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public EmpresaTaxi() {
	}

	/** minimal constructor */
	public EmpresaTaxi(int idEmpresaTaxi, Empresa empresa) {
		this.idEmpresaTaxi = idEmpresaTaxi;
		this.empresa = empresa;
	}

	/** full constructor */
	public EmpresaTaxi(int idEmpresaTaxi, Empresa empresa, Set interfaceSmses,
			Set convenios, Set operadors, Set operadors_1,
			Set interfaceSmses_1, Set convenios_1, Set taxis, Set taxis_1) {
		this.idEmpresaTaxi = idEmpresaTaxi;
		this.empresa = empresa;
		this.interfaceSmses = interfaceSmses;
		this.convenios = convenios;
		this.operadors = operadors;
		this.operadors_1 = operadors_1;
		this.interfaceSmses_1 = interfaceSmses_1;
		this.convenios_1 = convenios_1;
		this.taxis = taxis;
		this.taxis_1 = taxis_1;
	}

	// Property accessors
	public int getIdEmpresaTaxi() {
		return this.idEmpresaTaxi;
	}

	public void setIdEmpresaTaxi(int idEmpresaTaxi) {
		this.idEmpresaTaxi = idEmpresaTaxi;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Set getInterfaceSmses() {
		return this.interfaceSmses;
	}

	public void setInterfaceSmses(Set interfaceSmses) {
		this.interfaceSmses = interfaceSmses;
	}

	public Set getConvenios() {
		return this.convenios;
	}

	public void setConvenios(Set convenios) {
		this.convenios = convenios;
	}

	public Set getOperadors() {
		return this.operadors;
	}

	public void setOperadors(Set operadors) {
		this.operadors = operadors;
	}

	public Set getOperadors_1() {
		return this.operadors_1;
	}

	public void setOperadors_1(Set operadors_1) {
		this.operadors_1 = operadors_1;
	}

	public Set getInterfaceSmses_1() {
		return this.interfaceSmses_1;
	}

	public void setInterfaceSmses_1(Set interfaceSmses_1) {
		this.interfaceSmses_1 = interfaceSmses_1;
	}

	public Set getConvenios_1() {
		return this.convenios_1;
	}

	public void setConvenios_1(Set convenios_1) {
		this.convenios_1 = convenios_1;
	}

	public Set getTaxis() {
		return this.taxis;
	}

	public void setTaxis(Set taxis) {
		this.taxis = taxis;
	}

	public Set getTaxis_1() {
		return this.taxis_1;
	}

	public void setTaxis_1(Set taxis_1) {
		this.taxis_1 = taxis_1;
	}

}
