package br.com.digitaxi.pessoa.cidade;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.pessoa.uf.Uf;

/**
 * Cidade generated by hbm2java
 */
public class Cidade implements java.io.Serializable {

	// Fields    

	private int idCidade;

	private Uf uf;

	private String nome;

	private Set enderecos = new HashSet(0);

	private Set enderecos_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Cidade() {
	}

	/** minimal constructor */
	public Cidade(int idCidade, Uf uf, String nome) {
		this.idCidade = idCidade;
		this.uf = uf;
		this.nome = nome;
	}

	/** full constructor */
	public Cidade(int idCidade, Uf uf, String nome, Set enderecos,
			Set enderecos_1) {
		this.idCidade = idCidade;
		this.uf = uf;
		this.nome = nome;
		this.enderecos = enderecos;
		this.enderecos_1 = enderecos_1;
	}

	// Property accessors
	public int getIdCidade() {
		return this.idCidade;
	}

	public void setIdCidade(int idCidade) {
		this.idCidade = idCidade;
	}

	public Uf getUf() {
		return this.uf;
	}

	public void setUf(Uf uf) {
		this.uf = uf;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set enderecos) {
		this.enderecos = enderecos;
	}

	public Set getEnderecos_1() {
		return this.enderecos_1;
	}

	public void setEnderecos_1(Set enderecos_1) {
		this.enderecos_1 = enderecos_1;
	}

}
