package br.com.digitaxi.ativo.marca;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca implements java.io.Serializable {

	// Fields    

	private short idMarca;

	private String nome;

	private Set modelos = new HashSet(0);

	private Set modelos_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Marca() {
	}

	/** minimal constructor */
	public Marca(short idMarca) {
		this.idMarca = idMarca;
	}

	/** full constructor */
	public Marca(short idMarca, String nome, Set modelos, Set modelos_1) {
		this.idMarca = idMarca;
		this.nome = nome;
		this.modelos = modelos;
		this.modelos_1 = modelos_1;
	}

	// Property accessors
	public short getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(short idMarca) {
		this.idMarca = idMarca;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getModelos() {
		return this.modelos;
	}

	public void setModelos(Set modelos) {
		this.modelos = modelos;
	}

	public Set getModelos_1() {
		return this.modelos_1;
	}

	public void setModelos_1(Set modelos_1) {
		this.modelos_1 = modelos_1;
	}

}
