set search_path to schema_teste;

CREATE SEQUENCE SEQ_MARCA
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_UF
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_PERFIL
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_MENU
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_MODELO
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_USUARIO
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_CIDADE
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_EMPRESA
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_EMPRESA_ADMINISTRADORA
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_EMPRESA_TAXI
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_PESSOA
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_CLIENTE
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_CELULAR
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_EMPRESA_CONVENIADA
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_EMPRESA_OPERADORA_CELULAR
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_OPERADOR
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_ENDERECO
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_CONVENIO
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_CLIENTE_CONVENIO
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_NOME_ENDERECO
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_INTERFACE_SMS
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_PROPRIETARIO
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_TAXI
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_INTERFACE_AVL
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE SEQUENCE SEQ_MOTORISTA
   INCREMENT 1
   START 1
   MAXVALUE 4294967296;
CREATE TABLE MARCA (
  ID_MARCA INT2,
  NOME VARCHAR NULL,
  PRIMARY KEY(ID_MARCA)
);
CREATE TABLE UF (
  ID_UF INT2,
  NOME VARCHAR NOT NULL,
  PRIMARY KEY(ID_UF)
);
CREATE TABLE PERFIL (
  ID_PERFIL INT2,
  NOME VARCHAR(45) NOT NULL,
  DESCRICAO VARCHAR(255) NULL,
  PRIMARY KEY(ID_PERFIL)
);
CREATE TABLE MENU (
  ID_MENU INT2,
  ID_MENU_PAI INTEGER  NOT NULL,
  ID_PERFIL INTEGER  NOT NULL,
  NOME VARCHAR(20) NOT NULL,
  DESCRICAO VARCHAR(255) NULL,
  URL VARCHAR NULL,
  PRIMARY KEY(ID_MENU)
);
CREATE TABLE MODELO (
  ID_MODELO INT2,
  ID_MARCA INTEGER  NOT NULL,
  NOME VARCHAR NULL,
  PRIMARY KEY(ID_MODELO)
);
CREATE TABLE USUARIO (
  ID_USUARIO INT4,
  ID_PERFIL INTEGER  NOT NULL,
  LOGIN VARCHAR(20) NOT NULL,
  SENHA VARCHAR(45) NOT NULL,
  DESCRICAO VARCHAR(255) NULL,
  PRIMARY KEY(ID_USUARIO)
);
CREATE TABLE CIDADE (
  ID_CIDADE INT4,
  ID_UF INTEGER  NOT NULL,
  NOME VARCHAR NOT NULL,
  PRIMARY KEY(ID_CIDADE)
);
CREATE TABLE EMPRESA (
  ID_EMPRESA INT4,
  ID_USUARIO INTEGER  NOT NULL,
  NOME VARCHAR NULL,
  CNPJ VARCHAR NULL,
  CONTATO VARCHAR NULL,
  TELEFONE VARCHAR NULL,
  FAX VARCHAR NULL,
  E_MAIL VARCHAR NULL,
  HOME VARCHAR NULL,
  DESCRICAO VARCHAR NULL,
  PRIMARY KEY(ID_EMPRESA)
);
CREATE TABLE EMPRESA_ADMINISTRADORA (
  ID_EMPRESA_ADMIN INT4,
  ID_EMPRESA INTEGER  NOT NULL,
  PRIMARY KEY(ID_EMPRESA_ADMIN)
);
CREATE TABLE EMPRESA_TAXI (
  ID_EMPRESA_TAXI INT4,
  ID_EMPRESA INTEGER  NOT NULL,
  PRIMARY KEY(ID_EMPRESA_TAXI)
);
CREATE TABLE PESSOA (
  ID_PESSOA INT4,
  ID_USUARIO INTEGER  NOT NULL,
  NOME VARCHAR NULL,
  CPF VARCHAR NULL,
  TELEFONE_RES INTEGER  NULL,
  CELULAR INTEGER  NULL,
  TELEFONE_COM INTEGER  NULL,
  E_MAIL VARCHAR NULL,
  DESCRICAO VARCHAR NULL,
  PRIMARY KEY(ID_PESSOA)
);
CREATE TABLE CLIENTE (
  ID_CLIENTE INT4,
  ID_PESSOA INTEGER  NOT NULL,
  STA_EVENTUAL VARCHAR(1) NOT NULL,
  PRIMARY KEY(ID_CLIENTE)
);
CREATE TABLE CELULAR (
  ID_CELULAR INT4,
  ID_CLIENTE INTEGER  NOT NULL,
  PRIMARY KEY(ID_CELULAR)
);
CREATE TABLE EMPRESA_CONVENIADA (
  ID_EMPRESA_CONVENIADA INT4,
  ID_EMPRESA INTEGER  NOT NULL,
  PRIMARY KEY(ID_EMPRESA_CONVENIADA)
);
CREATE TABLE EMPRESA_OPERADORA_CELULAR (
  ID_EMPRESA_OPERADORA_CELULAR INT4,
  ID_EMPRESA INTEGER  NOT NULL,
  PRIMARY KEY(ID_EMPRESA_OPERADORA_CELULAR)
);
CREATE TABLE OPERADOR (
  ID_OPERADOR INT4,
  ID_EMPRESA_TAXI INTEGER  NOT NULL,
  ID_PESSOA INTEGER  NOT NULL,
  PRIMARY KEY(ID_OPERADOR)
);
CREATE TABLE ENDERECO (
  ID_ENDERECO INT4,
  ID_PESSOA INTEGER  NOT NULL,
  ID_CIDADE INTEGER  NOT NULL,
  LOGRADOURO VARCHAR NULL,
  BARRIO VARCHAR NULL,
  CEP VARCHAR NULL,
  PRIMARY KEY(ID_ENDERECO)
);
CREATE TABLE CONVENIO (
  ID_CONVENIO INT4,
  ID_EMPRESA_CONVENIADA INTEGER  NOT NULL,
  ID_EMPRESA_TAXI INTEGER  NOT NULL,
  PRIMARY KEY(ID_CONVENIO)
);
CREATE TABLE CLIENTE_CONVENIO (
  ID_CLIENTE_CONVENIO INT4,
  ID_CLIENTE INTEGER  NOT NULL,
  ID_CONVENIO INTEGER  NOT NULL,
  PRIMARY KEY(ID_CLIENTE_CONVENIO)
);
CREATE TABLE NOME_ENDERECO (
  ID_NOME_ENDERECO INT4 NOT NULL,
  ID_CELULAR INTEGER  NOT NULL,
  ID_ENDERECO INTEGER  NOT NULL,
  PRIMARY KEY(ID_NOME_ENDERECO)
);
CREATE TABLE INTERFACE_SMS (
  ID_INTERFACE_SMS INT4,
  ID_EMPRESA_OPERADORA_CELULAR INTEGER  NOT NULL,
  ID_EMPRESA_TAXI INTEGER  NOT NULL,
  NUM_SMS VARCHAR(10) NOT NULL,
  PRIMARY KEY(ID_INTERFACE_SMS)
);
CREATE TABLE PROPRIETARIO (
  ID_PROPRIETARIO INT4,
  ID_PESSOA INTEGER  NULL,
  PRIMARY KEY(ID_PROPRIETARIO)
);
CREATE TABLE TAXI (
  ID_TAXI INT4,
  ID_PROPRIETARIO INTEGER  NOT NULL,
  ID_MODELO INTEGER  NOT NULL,
  ID_EMPRESA_TAXI INTEGER  NOT NULL,
  ANO INTEGER  NULL,
  COR VARCHAR NULL,
  PLACA VARCHAR NULL,
  PRIMARY KEY(ID_TAXI)
);
CREATE TABLE INTERFACE_AVL (
  ID_INTERFACE_AVL INT4,
  ID_TAXI INTEGER  NOT NULL,
  PRIMARY KEY(ID_INTERFACE_AVL)
);
CREATE TABLE MOTORISTA (
  ID_MOTORISTA INT4,
  ID_TAXI INTEGER  NOT NULL,
  ID_PESSOA INTEGER  NOT NULL,
  CARTERA INTEGER  NULL,
  VENCIMENTO INTEGER  NULL,
  PRIMARY KEY(ID_MOTORISTA)
);
CREATE INDEX IDX_MENU_PERFIL on MENU
 (ID_PERFIL);
CREATE INDEX IDX_MENU_PAI on MENU
 (ID_MENU_PAI);
ALTER TABLE MENU
 ADD FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFIL(ID_PERFIL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE MENU
 ADD FOREIGN KEY (ID_MENU_PAI)
    REFERENCES MENU(ID_MENU)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_MODELO_MARCA on MODELO
 (ID_MARCA);
ALTER TABLE MODELO
 ADD FOREIGN KEY (ID_MARCA)
    REFERENCES MARCA(ID_MARCA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_USUARIO_PERFIL on USUARIO
 (ID_PERFIL);
ALTER TABLE USUARIO
 ADD FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFIL(ID_PERFIL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_CIDADE_UF on CIDADE
 (ID_UF);
ALTER TABLE CIDADE
 ADD FOREIGN KEY (ID_UF)
    REFERENCES UF(ID_UF)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_EMPRESA_USUARIO on EMPRESA
 (ID_USUARIO);
ALTER TABLE EMPRESA
 ADD FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_EMPRESA_ADMINISTRADORA_EMPRESA on EMPRESA_ADMINISTRADORA
 (ID_EMPRESA);
ALTER TABLE EMPRESA_ADMINISTRADORA
 ADD FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_EMPRESA_TAXI_EMPRESA on EMPRESA_TAXI
 (ID_EMPRESA);
ALTER TABLE EMPRESA_TAXI
 ADD FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_PESSOA_USUARIO on PESSOA
 (ID_USUARIO);
ALTER TABLE PESSOA
 ADD FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_CLIENTE_PESSOA on CLIENTE
 (ID_PESSOA);
ALTER TABLE CLIENTE
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_CELULAR_CLIENTE on CELULAR
 (ID_CLIENTE);
ALTER TABLE CELULAR
 ADD FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_EMPRESA_CONVENIADA_EMPRESA on EMPRESA_CONVENIADA
 (ID_EMPRESA);
ALTER TABLE EMPRESA_CONVENIADA
 ADD FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_EMPRESA_OPERADORA_EMPRESA on EMPRESA_OPERADORA_CELULAR
 (ID_EMPRESA);
ALTER TABLE EMPRESA_OPERADORA_CELULAR
 ADD FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_OPERADOR_PESSOA on OPERADOR
 (ID_PESSOA);
CREATE INDEX IDX_OPERADOR_EMPRESA_TAXI on OPERADOR
 (ID_EMPRESA_TAXI);
ALTER TABLE OPERADOR
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE OPERADOR
 ADD FOREIGN KEY (ID_EMPRESA_TAXI)
    REFERENCES EMPRESA_TAXI(ID_EMPRESA_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_ENDERECO_PESSOA on ENDERECO
 (ID_PESSOA);
CREATE INDEX IDX_ENDERECO_CIDADE on ENDERECO
 (ID_CIDADE);
ALTER TABLE ENDERECO
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE ENDERECO
 ADD FOREIGN KEY (ID_CIDADE)
    REFERENCES CIDADE(ID_CIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_CONVENIO_EMPRESA_CONVENIADA on CONVENIO
 (ID_EMPRESA_CONVENIADA);
CREATE INDEX IDX_CONVENIO_EMPRESA_TAXI on CONVENIO
 (ID_EMPRESA_TAXI);
ALTER TABLE CONVENIO
 ADD FOREIGN KEY (ID_EMPRESA_CONVENIADA)
    REFERENCES EMPRESA_CONVENIADA(ID_EMPRESA_CONVENIADA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CONVENIO
 ADD FOREIGN KEY (ID_EMPRESA_TAXI)
    REFERENCES EMPRESA_TAXI(ID_EMPRESA_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_CLIENTE_CONVENIO_CONVENIO on CLIENTE_CONVENIO
 (ID_CONVENIO);
CREATE INDEX IDX_CLIENTE_CONVENIO_CLIENTE on CLIENTE_CONVENIO
 (ID_CLIENTE);
ALTER TABLE CLIENTE_CONVENIO
 ADD FOREIGN KEY (ID_CONVENIO)
    REFERENCES CONVENIO(ID_CONVENIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CLIENTE_CONVENIO
 ADD FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_NOME_ENDERECO_ENDERECO on NOME_ENDERECO
 (ID_ENDERECO);
ALTER TABLE NOME_ENDERECO
 ADD FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO(ID_ENDERECO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE NOME_ENDERECO
 ADD FOREIGN KEY (ID_CELULAR)
    REFERENCES CELULAR(ID_CELULAR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_INTERFACE_SMS_EMPRESA_TAXI on INTERFACE_SMS
 (ID_EMPRESA_TAXI);
CREATE INDEX IDX_INTERFACE_SMS_EMPRESA_OPERADORA_CELULAR on INTERFACE_SMS
 (ID_EMPRESA_OPERADORA_CELULAR);
ALTER TABLE INTERFACE_SMS
 ADD FOREIGN KEY (ID_EMPRESA_TAXI)
    REFERENCES EMPRESA_TAXI(ID_EMPRESA_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE INTERFACE_SMS
 ADD FOREIGN KEY (ID_EMPRESA_OPERADORA_CELULAR)
    REFERENCES EMPRESA_OPERADORA_CELULAR(ID_EMPRESA_OPERADORA_CELULAR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_PROPRIETARIO_PESSOA on PROPRIETARIO
 (ID_PESSOA);
ALTER TABLE PROPRIETARIO
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_TAXI_EMPRESA_TAXI on TAXI
 (ID_EMPRESA_TAXI);
CREATE INDEX IDX_TAXI_MODELO on TAXI
 (ID_MODELO);
CREATE INDEX IDX_TAXI_PROPRIETARIO on TAXI
 (ID_PROPRIETARIO);
ALTER TABLE TAXI
 ADD FOREIGN KEY (ID_EMPRESA_TAXI)
    REFERENCES EMPRESA_TAXI(ID_EMPRESA_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE TAXI
 ADD FOREIGN KEY (ID_MODELO)
    REFERENCES MODELO(ID_MODELO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE TAXI
 ADD FOREIGN KEY (ID_PROPRIETARIO)
    REFERENCES PROPRIETARIO(ID_PROPRIETARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_INTERFACE_AVL_TAXI on INTERFACE_AVL
 (ID_TAXI);
ALTER TABLE INTERFACE_AVL
 ADD FOREIGN KEY (ID_TAXI)
    REFERENCES TAXI(ID_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
CREATE INDEX IDX_MOTORISTA_TAXI on MOTORISTA
 (ID_TAXI);
CREATE INDEX IDX_MOTORISTA_PESSOA on MOTORISTA
 (ID_PESSOA);
ALTER TABLE MOTORISTA
 ADD FOREIGN KEY (ID_TAXI)
    REFERENCES TAXI(ID_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE MOTORISTA
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE MENU
 ADD FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFIL(ID_PERFIL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE MENU
 ADD FOREIGN KEY (ID_MENU_PAI)
    REFERENCES MENU(ID_MENU)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE MODELO
 ADD FOREIGN KEY (ID_MARCA)
    REFERENCES MARCA(ID_MARCA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE USUARIO
 ADD FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFIL(ID_PERFIL)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CIDADE
 ADD FOREIGN KEY (ID_UF)
    REFERENCES UF(ID_UF)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE EMPRESA
 ADD FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE EMPRESA_ADMINISTRADORA
 ADD FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE EMPRESA_TAXI
 ADD FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE PESSOA
 ADD FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CLIENTE
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CELULAR
 ADD FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE EMPRESA_CONVENIADA
 ADD FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE EMPRESA_OPERADORA_CELULAR
 ADD FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE OPERADOR
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE OPERADOR
 ADD FOREIGN KEY (ID_EMPRESA_TAXI)
    REFERENCES EMPRESA_TAXI(ID_EMPRESA_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE ENDERECO
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE ENDERECO
 ADD FOREIGN KEY (ID_CIDADE)
    REFERENCES CIDADE(ID_CIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CONVENIO
 ADD FOREIGN KEY (ID_EMPRESA_CONVENIADA)
    REFERENCES EMPRESA_CONVENIADA(ID_EMPRESA_CONVENIADA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CONVENIO
 ADD FOREIGN KEY (ID_EMPRESA_TAXI)
    REFERENCES EMPRESA_TAXI(ID_EMPRESA_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CLIENTE_CONVENIO
 ADD FOREIGN KEY (ID_CONVENIO)
    REFERENCES CONVENIO(ID_CONVENIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE CLIENTE_CONVENIO
 ADD FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE NOME_ENDERECO
 ADD FOREIGN KEY (ID_ENDERECO)
    REFERENCES ENDERECO(ID_ENDERECO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE NOME_ENDERECO
 ADD FOREIGN KEY (ID_CELULAR)
    REFERENCES CELULAR(ID_CELULAR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE INTERFACE_SMS
 ADD FOREIGN KEY (ID_EMPRESA_TAXI)
    REFERENCES EMPRESA_TAXI(ID_EMPRESA_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE INTERFACE_SMS
 ADD FOREIGN KEY (ID_EMPRESA_OPERADORA_CELULAR)
    REFERENCES EMPRESA_OPERADORA_CELULAR(ID_EMPRESA_OPERADORA_CELULAR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE PROPRIETARIO
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE TAXI
 ADD FOREIGN KEY (ID_EMPRESA_TAXI)
    REFERENCES EMPRESA_TAXI(ID_EMPRESA_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE TAXI
 ADD FOREIGN KEY (ID_MODELO)
    REFERENCES MODELO(ID_MODELO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE TAXI
 ADD FOREIGN KEY (ID_PROPRIETARIO)
    REFERENCES PROPRIETARIO(ID_PROPRIETARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE INTERFACE_AVL
 ADD FOREIGN KEY (ID_TAXI)
    REFERENCES TAXI(ID_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE MOTORISTA
 ADD FOREIGN KEY (ID_TAXI)
    REFERENCES TAXI(ID_TAXI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE MOTORISTA
 ADD FOREIGN KEY (ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
