/**
 * 
 */
package unbbayes.prs.mebn.kb.extension;

import unbbayes.controller.mebn.IMEBNMediator;
import unbbayes.prs.mebn.MultiEntityBayesianNetwork;
import unbbayes.prs.mebn.kb.KnowledgeBase;

/**
 * This interface builds an instance of {@link KnowledgeBase},
 * and it is used by the UnBBayes' plugin infrastructure as a 
 * main interface for Knowledge Base's plugin.
 * Every plugin extending the KnowledgeBase extension point of
 * MEBN module must implement this interface.
 * 
 * Implementors must provide a default constructor, with no arguments!
 * 
 * @author Shou Matsumoto
 *
 */
public interface IKnowledgeBaseBuilder {
	
	/**
	 * Builds an instance of {@link KnowledgeBase},
	 * mostly using the parameters passed from {@link #setName(String)}
	 * @return instance of {@link KnowledgeBase}
	 * @throws InstantiationException when we fail to build an instance
	 * @deprecated use {@link #buildKB(MultiEntityBayesianNetwork, IMEBNMediator)} instead
	 */
	@Deprecated
	public KnowledgeBase buildKB() throws InstantiationException;
	
	/**
	 * Builds an instance of {@link KnowledgeBase},
	 * mostly using the parameters passed from {@link #setName(String)}
	 * @param mebn : the MEBN to run knowledge base
	 * @param mediator : object containing references to some I/O and GUI elements.
	 * @return instance of {@link KnowledgeBase}
	 * @throws InstantiationException when we fail to build an instance
	 */
	public KnowledgeBase buildKB(MultiEntityBayesianNetwork mebn, IMEBNMediator mediator) throws InstantiationException;
	
	
	/**
	 * Obtains a name for the KnowledgeBase to be generated by this builder.
	 *  This is used by the program to display a name to a user.
	 * @return a name
	 */
	public String getName();
	
	/**
	 * Obtains a name for the KnowledgeBase to be generated by this builder.
	 *  This is used by the program to display a name to a user.
	 * @param name : name of the KB
	 */
	public void setName(String name);
}
