package br.com.digitaxi.empresa.interfacesms;

import br.com.digitaxi.empresa.empresaoperadoracelular.EmpresaOperadoraCelular;
import br.com.digitaxi.empresa.empresataxi.EmpresaTaxi;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

/**
 * InterfaceSms generated by hbm2java
 */
public class InterfaceSms implements java.io.Serializable {

	// Fields    

	private int idInterfaceSms;

	private EmpresaTaxi empresaTaxi;

	private EmpresaOperadoraCelular empresaOperadoraCelular;

	private String numSms;

	// Constructors

	/** default constructor */
	public InterfaceSms() {
	}

	/** full constructor */
	public InterfaceSms(int idInterfaceSms, EmpresaTaxi empresaTaxi,
			EmpresaOperadoraCelular empresaOperadoraCelular, String numSms) {
		this.idInterfaceSms = idInterfaceSms;
		this.empresaTaxi = empresaTaxi;
		this.empresaOperadoraCelular = empresaOperadoraCelular;
		this.numSms = numSms;
	}

	// Property accessors
	public int getIdInterfaceSms() {
		return this.idInterfaceSms;
	}

	public void setIdInterfaceSms(int idInterfaceSms) {
		this.idInterfaceSms = idInterfaceSms;
	}

	public EmpresaTaxi getEmpresaTaxi() {
		return this.empresaTaxi;
	}

	public void setEmpresaTaxi(EmpresaTaxi empresaTaxi) {
		this.empresaTaxi = empresaTaxi;
	}

	public EmpresaOperadoraCelular getEmpresaOperadoraCelular() {
		return this.empresaOperadoraCelular;
	}

	public void setEmpresaOperadoraCelular(
			EmpresaOperadoraCelular empresaOperadoraCelular) {
		this.empresaOperadoraCelular = empresaOperadoraCelular;
	}

	public String getNumSms() {
		return this.numSms;
	}

	public void setNumSms(String numSms) {
		this.numSms = numSms;
	}

}
