package br.com.digitaxi.pessoa.motorista;

import br.com.digitaxi.ativo.taxi.Taxi;
import br.com.digitaxi.pessoa.pessoa.Pessoa;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

/**
 * Motorista generated by hbm2java
 */
public class Motorista implements java.io.Serializable {

	// Fields    

	private int idMotorista;

	private Taxi taxi;

	private Pessoa pessoa;

	private Integer cartera;

	private Integer vencimento;

	// Constructors

	/** default constructor */
	public Motorista() {
	}

	/** minimal constructor */
	public Motorista(int idMotorista, Taxi taxi, Pessoa pessoa) {
		this.idMotorista = idMotorista;
		this.taxi = taxi;
		this.pessoa = pessoa;
	}

	/** full constructor */
	public Motorista(int idMotorista, Taxi taxi, Pessoa pessoa,
			Integer cartera, Integer vencimento) {
		this.idMotorista = idMotorista;
		this.taxi = taxi;
		this.pessoa = pessoa;
		this.cartera = cartera;
		this.vencimento = vencimento;
	}

	// Property accessors
	public int getIdMotorista() {
		return this.idMotorista;
	}

	public void setIdMotorista(int idMotorista) {
		this.idMotorista = idMotorista;
	}

	public Taxi getTaxi() {
		return this.taxi;
	}

	public void setTaxi(Taxi taxi) {
		this.taxi = taxi;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Integer getCartera() {
		return this.cartera;
	}

	public void setCartera(Integer cartera) {
		this.cartera = cartera;
	}

	public Integer getVencimento() {
		return this.vencimento;
	}

	public void setVencimento(Integer vencimento) {
		this.vencimento = vencimento;
	}

}
