package br.com.digitaxi.empresa.empresaoperadoracelular;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.empresa.empresa.Empresa;

/**
 * EmpresaOperadoraCelular generated by hbm2java
 */
public class EmpresaOperadoraCelular implements java.io.Serializable {

	// Fields    

	private int idEmpresaOperadoraCelular;

	private Empresa empresa;

	private Set interfaceSmses = new HashSet(0);

	private Set interfaceSmses_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public EmpresaOperadoraCelular() {
	}

	/** minimal constructor */
	public EmpresaOperadoraCelular(int idEmpresaOperadoraCelular,
			Empresa empresa) {
		this.idEmpresaOperadoraCelular = idEmpresaOperadoraCelular;
		this.empresa = empresa;
	}

	/** full constructor */
	public EmpresaOperadoraCelular(int idEmpresaOperadoraCelular,
			Empresa empresa, Set interfaceSmses, Set interfaceSmses_1) {
		this.idEmpresaOperadoraCelular = idEmpresaOperadoraCelular;
		this.empresa = empresa;
		this.interfaceSmses = interfaceSmses;
		this.interfaceSmses_1 = interfaceSmses_1;
	}

	// Property accessors
	public int getIdEmpresaOperadoraCelular() {
		return this.idEmpresaOperadoraCelular;
	}

	public void setIdEmpresaOperadoraCelular(int idEmpresaOperadoraCelular) {
		this.idEmpresaOperadoraCelular = idEmpresaOperadoraCelular;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Set getInterfaceSmses() {
		return this.interfaceSmses;
	}

	public void setInterfaceSmses(Set interfaceSmses) {
		this.interfaceSmses = interfaceSmses;
	}

	public Set getInterfaceSmses_1() {
		return this.interfaceSmses_1;
	}

	public void setInterfaceSmses_1(Set interfaceSmses_1) {
		this.interfaceSmses_1 = interfaceSmses_1;
	}

}
