package br.com.digitaxi.controleacesso.usuario;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.controleacesso.perfil.Perfil;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	// Fields    

	private int idUsuario;

	private Perfil perfil;

	private String login;

	private String senha;

	private String descricao;

	private Set pessoas = new HashSet(0);

	private Set empresas = new HashSet(0);

	// Constructors

	/** default constructor */
	public Usuario() {
	}

	/** minimal constructor */
	public Usuario(int idUsuario, Perfil perfil, String login, String senha) {
		this.idUsuario = idUsuario;
		this.perfil = perfil;
		this.login = login;
		this.senha = senha;
	}

	/** full constructor */
	public Usuario(int idUsuario, Perfil perfil, String login, String senha,
			String descricao, Set pessoas, Set pessoas_1, Set empresas,
			Set empresas_1) {
		this.idUsuario = idUsuario;
		this.perfil = perfil;
		this.login = login;
		this.senha = senha;
		this.descricao = descricao;
		this.pessoas = pessoas;
		this.empresas = empresas;
	}

	// Property accessors
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Set getPessoas() {
		return this.pessoas;
	}

	public void setPessoas(Set pessoas) {
		this.pessoas = pessoas;
	}

	public Set getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set empresas) {
		this.empresas = empresas;
	}

}
