package br.com.digitaxi.ativo.interfaceavl;

import br.com.digitaxi.ativo.taxi.Taxi;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

/**
 * InterfaceAvl generated by hbm2java
 */
public class InterfaceAvl implements java.io.Serializable {

	// Fields    

	private int idInterfaceAvl;

	private Taxi taxi;

	// Constructors

	/** default constructor */
	public InterfaceAvl() {
	}

	/** full constructor */
	public InterfaceAvl(int idInterfaceAvl, Taxi taxi) {
		this.idInterfaceAvl = idInterfaceAvl;
		this.taxi = taxi;
	}

	// Property accessors
	public int getIdInterfaceAvl() {
		return this.idInterfaceAvl;
	}

	public void setIdInterfaceAvl(int idInterfaceAvl) {
		this.idInterfaceAvl = idInterfaceAvl;
	}

	public Taxi getTaxi() {
		return this.taxi;
	}

	public void setTaxi(Taxi taxi) {
		this.taxi = taxi;
	}

}
