package br.com.digitaxi.empresa.empresaadministradora;

import br.com.digitaxi.empresa.empresa.Empresa;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

/**
 * EmpresaAdministradora generated by hbm2java
 */
public class EmpresaAdministradora implements java.io.Serializable {

	// Fields    

	private int idEmpresaAdmin;

	private Empresa empresa;

	// Constructors

	/** default constructor */
	public EmpresaAdministradora() {
	}

	/** full constructor */
	public EmpresaAdministradora(int idEmpresaAdmin, Empresa empresa) {
		this.idEmpresaAdmin = idEmpresaAdmin;
		this.empresa = empresa;
	}

	// Property accessors
	public int getIdEmpresaAdmin() {
		return this.idEmpresaAdmin;
	}

	public void setIdEmpresaAdmin(int idEmpresaAdmin) {
		this.idEmpresaAdmin = idEmpresaAdmin;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

}
