package br.com.digitaxi.controleacesso.menu;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.controleacesso.perfil.Perfil;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	// Fields    

	private short idMenu;

	private Menu menuPai;

	private Perfil perfil;

	private String nome;

	private String descricao;

	private String url;
	
	private String icon;
	
	private int prioridade;

	private Set menus = new HashSet(0);

	// Constructors

	/** default constructor */
	public Menu() {
	}

	/** minimal constructor */
	public Menu(short idMenu, Menu menuPai, Perfil perfil, String nome) {
		this.idMenu = idMenu;
		this.menuPai = menuPai;
		this.perfil = perfil;
		this.nome = nome;
	}

	/** full constructor */
	public Menu(short idMenu, Menu menuPai, Perfil perfil, String nome,
			String descricao, String url, Set menus, Set menus_1) {
		this.idMenu = idMenu;
		this.menuPai = menuPai;
		this.perfil = perfil;
		this.nome = nome;
		this.descricao = descricao;
		this.url = url;
		this.menus = menus;
	}

	// Property accessors
	public short getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(short idMenu) {
		this.idMenu = idMenu;
	}

	public Menu getMenuPai() {
		return this.menuPai;
	}

	public void setMenuPai(Menu menuPai) {
		this.menuPai = menuPai;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Set getMenus() {
		return this.menus;
	}

	public void setMenus(Set menus) {
		this.menus = menus;
	}

	public int getPrioridade() {
		return prioridade;
	}

	public void setPrioridade(int prioridade) {
		this.prioridade = prioridade;
	}

}
