package br.com.digitaxi.pessoa.cliente;

// Generated 23/03/2007 15:18:07 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import br.com.digitaxi.pessoa.pessoa.Pessoa;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	// Fields    

	private int idCliente;

	private Pessoa pessoa;

	private String staEventual;

	private Set clienteConvenios = new HashSet(0);

	private Set clienteConvenios_1 = new HashSet(0);

	private Set celulars = new HashSet(0);

	private Set celulars_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Cliente() {
	}

	/** minimal constructor */
	public Cliente(int idCliente, Pessoa pessoa, String staEventual) {
		this.idCliente = idCliente;
		this.pessoa = pessoa;
		this.staEventual = staEventual;
	}

	/** full constructor */
	public Cliente(int idCliente, Pessoa pessoa, String staEventual,
			Set clienteConvenios, Set clienteConvenios_1, Set celulars,
			Set celulars_1) {
		this.idCliente = idCliente;
		this.pessoa = pessoa;
		this.staEventual = staEventual;
		this.clienteConvenios = clienteConvenios;
		this.clienteConvenios_1 = clienteConvenios_1;
		this.celulars = celulars;
		this.celulars_1 = celulars_1;
	}

	// Property accessors
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public String getStaEventual() {
		return this.staEventual;
	}

	public void setStaEventual(String staEventual) {
		this.staEventual = staEventual;
	}

	public Set getClienteConvenios() {
		return this.clienteConvenios;
	}

	public void setClienteConvenios(Set clienteConvenios) {
		this.clienteConvenios = clienteConvenios;
	}

	public Set getClienteConvenios_1() {
		return this.clienteConvenios_1;
	}

	public void setClienteConvenios_1(Set clienteConvenios_1) {
		this.clienteConvenios_1 = clienteConvenios_1;
	}

	public Set getCelulars() {
		return this.celulars;
	}

	public void setCelulars(Set celulars) {
		this.celulars = celulars;
	}

	public Set getCelulars_1() {
		return this.celulars_1;
	}

	public void setCelulars_1(Set celulars_1) {
		this.celulars_1 = celulars_1;
	}

}
